name = "baby-sandbox"
author = "unvariant"
description = "How many different ways are there to make a syscall?\n\n{{chal.url}}"
provide = [ "./dist.tar.xz",]

[flag]
file = "chal/flag.txt"

[containers.chal]
build = "./chal"
ports = [ 5000,]

[expose.chal]
target = 5000
tcp = 1341

[containers.chal.limits]
cpu = 1
mem = 256
