name = "uwu"
author = "unvariant"
description = "uwu"
provide = []
flag = "uwu"
hidden = true

[containers.chal]
build = "."
ports = [ 5000,]

[expose.chal]
target = 5000
tcp = 4141

[containers.chal.limits]
cpu = 1
mem = 256
