name: publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/setup-buildx-action@v2.0.0
      - uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }},ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
