name = "cell-service"
author = "hellopir2"
description = """
The signal I'm getting up here is unfathomably bad, and I think that's why my flag is taking so long to decode. Can you help?
"""
provide = [ "./cell-service.py", "./out.zip"]

[flag]
file = "flag.txt"