name = "lahoot-async"
author = "smashmaster"
description = """
# Lahoot Async
Due to the great tragedy called budget cuts in infra, we've downsized lahoot and have had to reduce upon the realtime interactions*. Because of this you can expect the new version to include twice the cringe, and half the bandwidth usage (bandwidth usage may vary) because we have removed any use of websockets or socket.io. we also lost our budget for the database and images on the quiz but at the cost of possibly better infra this year.

But ignoring that, let us enjoy the release of the next cringe "live" quiz game for AmateursCTF 2024. Unfortunately, due to uhm blatant cheating attempts we're unable to offer the source code at the moment until we can figure out how the cheaters are 100%ing nor can we offer any swag for this challenges sry =<. You can always get chips as swag technically tho =). oop last thing we forgot to mention, we couldn't afford actual questions so the robots wrote this year's questions. glhf

*ahem, certain people made scripts to "accidentally" dos the poor kubernetes last year ruining the fun.

**REMINDER: LAHOOT SOLVES DOESN'T AND NEVER WILL INVOLVE DOSING THE SERVER, WE WILL FIND YOU**

{{main.url}}
"""

flag = "amateursCTF{d0_y0u_ch3at_in_y0ur_0wn_sch00l_c0nt3sts?}"

[containers.main]
build = "."
limits.cpu = 1
limits.mem = 512
env.FLAG = "amateursCTF{d0_y0u_ch3at_in_y0ur_0wn_sch00l_c0nt3sts?}"

[expose.main]
target = 8000
http = "lahoot-async"
