name = "wumpus-leaks"
author = "smashmaster"
description = """
hopefully redacted enough, im kind of bad at this whole iphone photography thing so it took a few attempts to make this intentionally cringe msfrog in front of the flag, hopefully no one can guess the flag using this info
"""
provide = [ "./IMG_7276.jpg"]

[flag]
file = "flag.txt"