name = "crackbox"
author = "unvariant"
description = "Just another restricted qemu-user sandbox.\n\n{{chal.url}}"
provide = [ "./dist.tar.xz",]

[flag]
file = "chal/flag.txt"

[containers.chal]
build = "./chal"
ports = [ 5000,]

[expose.chal]
target = 5000
tcp = 1339

[containers.chal.limits]
cpu = 1
mem = 256
