name = "cookie"
author = "hellopir2"
description = """
What is life if not incomprehensible nonsense? Please untangle this for me. I'm hungry.

Flag is valid ascii.
"""
provide = [ "./checker.py", "./out.zip"]

[flag]
file = "flag.txt"
